# Generated by Django 3.0.7 on 2020-06-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='user')),
                ('session', models.CharField(max_length=20, verbose_name='session')),
                ('path', models.CharField(max_length=200, verbose_name='path')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
